# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup: 
    desc: Set up the development environment
    cmds:
      - pip install mkdocs-material
      - pip install mkdocs-git-revision-date-localized-plugin
      - pip install pymdown-extensions
      - task: setup:hooks
    silent: true

  setup:hooks:
    desc: Configure Git to use project hooks directory
    cmds:
      - git config core.hooksPath .githooks
      - chmod +x .githooks/pre-commit
      - echo "Git hooks configured! Pre-commit hook is now active for changelog generation."

  build:
    desc: Build the MkDocs site
    cmds:
      - mkdocs build --strict

  run:
    desc: Run codebaseinterface locally
    cmds:
      - mkdocs serve --livereload

  changelog:
    desc: Generate changelog using git-cliff
    cmds:
      - git cliff --output CHANGELOG.md

  changelog:unreleased:
    desc: Generate changelog for unreleased changes
    cmds:
      - git cliff --unreleased --output CHANGELOG.md

  changelog:update:
    desc: Update changelog with new commits since last tag
    cmds:
      - git cliff --latest --output CHANGELOG.md --prepend