# https://taskfile.dev

version: '3'

vars:
  SITE_NAME: Codebase Interface
  SITE_URL: https://codebase-interface.github.io

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  setup:
    desc: Set up the development environment
    cmds:
      - pip install --upgrade pip
      - pip install mkdocs-material>=9.0.0
      - pip install mkdocs-git-revision-date-localized-plugin
      - pip install mkdocs-multirepo-plugin
      - pip install mkdocs-mermaid2-plugin
      - pip install mkdocs-minify-plugin
      - pip install pymdown-extensions
      - echo "Setup complete!"

  install:
    desc: Install dependencies (alias for setup)
    cmds:
      - task: setup

  serve:
    desc: Serve the landing page locally with live reload
    cmds:
      - echo "Starting local development server..."
      - mkdocs serve --livereload --dev-addr 127.0.0.1:8000

  build:
    desc: Build the optimized landing page
    cmds:
      - echo "Building landing page..."
      - mkdocs build --strict --verbose

  deploy:
    desc: Deploy to GitHub Pages
    cmds:
      - echo "Deploying to GitHub Pages..."
      - mkdocs gh-deploy --force --verbose

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf site/
      - echo "Build artifacts cleaned"

  lint:
    desc: Lint markdown files
    cmds:
      - markdownlint --config .markdownlint.yml *.md

  validate:
    desc: Validate the complete site
    cmds:
      - task: lint
      - task: build

  stats:
    desc: Show site statistics
    cmds:
      - echo "Markdown files:"
      - find . -name '*.md' | wc -l
      - echo "CSS files:"
      - find assets -name '*.css' 2>/dev/null | wc -l || echo "0"
      - echo "JS files:"
      - find assets -name '*.js' 2>/dev/null | wc -l || echo "0"