# https://taskfile.dev

version: '3'

vars:
  SITE_NAME: Codebase Interface
  SITE_URL: https://codebase-interface.github.io

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  setup:
    desc: Set up the development environment
    cmds:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "✅ Python dependencies installed from requirements.txt"
      - echo "Note - For linting install markdownlint-cli globally"
      - python -c "import mkdocs_minify_plugin; print('✅ Minify plugin verified')" || echo "⚠️ Minify plugin not found"
      - echo "Setup complete!"

  install:
    desc: Install dependencies (alias for setup)
    cmds:
      - task: setup

  serve:
    desc: Serve the landing page locally with live reload
    cmds:
      - echo "Starting local development server..."
      - mkdocs serve --livereload --dev-addr 127.0.0.1:8000

  build:
    desc: Build the optimized landing page
    cmds:
      - echo "Building landing page..."
      - mkdocs build --strict --verbose

  build-production:
    desc: Build optimized production version
    cmds:
      - echo "Building production landing page..."
      - mkdocs build --strict --clean --verbose
      - echo "Production build complete!"

  deploy:
    desc: Deploy to GitHub Pages
    cmds:
      - echo "Deploying to GitHub Pages..."
      - mkdocs gh-deploy --force --verbose

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf site/
      - echo "Build artifacts cleaned"

  lint:
    desc: Lint markdown files
    cmds:
      - sh -c 'if command -v markdownlint > /dev/null 2>&1; then markdownlint --config .markdownlint.yml *.md docs/*.md && echo "✅ Markdown linting completed"; else echo "⚠️  markdownlint not found. Install with npm install -g markdownlint-cli" && echo "Skipping markdown linting..."; fi'

  validate:
    desc: Validate the complete site
    cmds:
      - task: lint
      - task: build

  stats:
    desc: Show site statistics
    cmds:
      - echo "Markdown files:"
      - find . -name '*.md' | wc -l
      - echo "CSS files:"
      - find docs/assets -name '*.css' 2>/dev/null | wc -l || echo "0"
      - echo "JS files:"
      - find docs/assets -name '*.js' 2>/dev/null | wc -l || echo "0"