# https://taskfile.dev

version: '3'

vars:
  SITE_NAME: Codebase Interface
  SITE_URL: https://codebase-interface.github.io

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  setup:
    desc: Set up the development environment
    cmds:
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "✅ Python dependencies installed from requirements.txt"
      - echo "Installing Node.js tools..."
      - npm install -g markdownlint-cli
      - echo "✅ Markdown linting tools installed"
      - python -c "import mkdocs_minify_plugin; print('✅ Minify plugin verified')" || echo "⚠️ Minify plugin not found"
      - echo "Setup complete!"

  install:
    desc: Install dependencies (alias for setup)
    cmds:
      - task: setup

  serve:
    desc: Serve the landing page locally with live reload
    cmds:
      - echo "Starting local development server..."
      - mkdocs serve --livereload --dev-addr 127.0.0.1:8000

  build:
    desc: Build the optimized landing page
    cmds:
      - echo "Building landing page..."
      - mkdocs build --strict --verbose

  build-production:
    desc: Build optimized production version
    cmds:
      - echo "Building production landing page..."
      - mkdocs build --strict --clean --verbose
      - touch site/.nojekyll
      - echo "✅ Added .nojekyll file for GitHub Pages"
      - echo "Production build complete!"

  deploy:
    desc: Deploy to GitHub Pages
    cmds:
      - echo "Deploying to GitHub Pages..."
      - mkdocs gh-deploy --force --verbose

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf site/
      - echo "Build artifacts cleaned"

  lint:
    desc: Lint markdown files
    cmds:
      - |
        if command -v markdownlint > /dev/null 2>&1; then
          if markdownlint --config .markdownlint.yml *.md docs/*.md; then
            echo "✅ Markdown linting passed"
          else
            echo "⚠️ Markdown linting found issues, but continuing deployment..."
            echo "Run 'markdownlint --config .markdownlint.yml *.md docs/*.md' to see details"
          fi
        else
          echo "⚠️ markdownlint not found. Run 'task setup' to install it"
          exit 1
        fi

  validate:
    desc: Validate the complete site
    cmds:
      - task: lint
      - echo "✅ Linting completed"
      - task: build
      - echo "✅ Build validation completed"

  stats:
    desc: Show site statistics
    cmds:
      - echo "Markdown files:"
      - find . -name '*.md' | wc -l
      - echo "CSS files:"
      - find docs/assets -name '*.css' 2>/dev/null | wc -l || echo "0"
      - echo "JS files:"
      - find docs/assets -name '*.js' 2>/dev/null | wc -l || echo "0"